<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <NrtTagMatch>cal/v[0-9]*</NrtTagMatch>

    <PackageId>AMWD.Protocols.CalDAV</PackageId>
    <AssemblyName>amwd-caldav</AssemblyName>
    <RootNamespace>AMWD.Protocols.CalDAV</RootNamespace>

    <Title>CalDAV implementation for .NET</Title>
    <Description>Using the DAV protocol to manage calendars and events.</Description>
    <PackageTags>CalDAV caldendar events</PackageTags>
  </PropertyGroup>

  <PropertyGroup Condition="$([System.Text.RegularExpressions.Regex]::IsMatch('$(CI_COMMIT_TAG)', '^cal\/v[0-9.]+'))">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ical.Net" Version="5.2.3" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CalDAV.Tests" />
  </ItemGroup>

</Project>
